global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'grafana'
  static_configs:
  - targets: [ 'localhost:3001' ]

- job_name: 'elasticsearch'
  static_configs:
  - targets: [ 'localhost:9200' ]

- job_name: 'kibana'
  static_configs:
  - targets: [ 'localhost:5601' ]

- job_name: 'harbor'
  static_configs:
  - targets: [ 'localhost:8082' ]

- job_name: 'confluence'
  static_configs:
  - targets: [ 'localhost:8090' ]

- job_name: 'jira'
  static_configs:
  - targets: [ 'localhost:8081' ]

- job_name: 'argocd'
  static_configs:
  - targets: [ 'localhost:8083' ]

- job_name: 'drawio'
  static_configs:
  - targets: [ 'localhost:8085' ]

- job_name: 'superset'
  static_configs:
  - targets: [ 'localhost:8086' ]

- job_name: 'kubecost'
  static_configs:
  - targets: [ 'localhost:8087' ]

- job_name: 'kion'
  static_configs:
  - targets: [ 'localhost:8088' ]

- job_name: 'vault'
  static_configs:
  - targets: [ 'localhost:8089' ]

- job_name: 'rocketchat'
  static_configs:
  - targets: [ 'localhost:8091' ]

- job_name: 'gitlab'
  static_configs:
  - targets: [ 'localhost:8080' ]

- job_name: 'api-gateway'
  static_configs:
  - targets: [ 'localhost:8000' ]

- job_name: 'portal'
  static_configs:
  - targets: [ 'localhost:3002' ]
